apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dep1
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      nodeSelector:
        env: demo
      containers:
      - name: helloworld
        image: karthequian/helloworld:latest