apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment1
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: api-server:v1
        imagePullPolicy: IfNotPresent