FROM ubuntu as builder

RUN apt-get update && apt-get install -y curl
RUN curl http://google.com | wc -c >google-size

FROM alpine

COPY --from=builder /google-size /google-size

ENTRYPOINT echo Google is this big; cat google-size
