Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian10"
    config.vm.network "private_network", ip: "192.168.33.61"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y default-jre
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        echo "alias ll='ls -l'" >> /root/.bashrc
    SHELL
end
