apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: server
    image: api-server:v1
  - name: client
    image: feniks/ubuntu-netbox
    command: ['/bin/sh']
    args: ['-c', 'while true; do curl -s http://localhost:8080/date; sleep 2; done']