Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "gitdemo.vagrant.vm"
        # Customize the amount of memory on the VM:
        vb.memory = "512"
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum install -y mc
        yum install -y --downloadonly git
    SHELL

    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end
