Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.network "private_network", ip: "192.168.33.60"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update #--allow-releaseinfo-change
        apt-get install -y git build-essential default-jre
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        echo "alias ll='ls -l'" >> /root/.bashrc
    SHELL
end
