apiVersion: v2
name: dummy
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.1.0"

dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.6
