Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.network "private_network", ip: "192.168.33.65"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update #--allow-releaseinfo-change
        apt-get install -y build-essential default-jre #git
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        echo "alias ll='ls -l'" >> /root/.bashrc

        # install jenkins
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
            /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
            https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
            /etc/apt/sources.list.d/jenkins.list > /dev/null
        apt-get update
        apt-get install jenkins

        # configure jenkins
        mkdir /var/lib/jenkins/init.groovy.d
        cp /vagrant/scripts/* /var/lib/jenkins/init.groovy.d/
        chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d/
        sed -i 's/^Environment="JAVA_OPTS=-Djava.awt.headless=true"/Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"/g' /lib/systemd/system/jenkins.service
        # -Dcasc.jenkins.config=${JENKINS_HOME}/casc_configs
        sed -i "s/^#TimeoutStartSec=90/TimeoutStartSec=180/g" /lib/systemd/system/jenkins.service

        systemctl daemon-reload
        systemctl restart jenkins
    SHELL
end
