apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.2.6
    chart: postgresql
    helm:
      values: |
        global:
          postgresql:
            auth:
              postgresPassword: "demopass"
              username: "demouser"
              password: "demopass"
              database: "demodb"

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true