apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret

        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
     
      volumes:
        - name: db-data
          persistentVolumeClaim: 
            claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
