apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80

        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_HOST
          value: mysql-svc

        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
     
      volumes:
        - name: wp-data
          persistentVolumeClaim: 
            claimName: pvc-wp
---
apiVersion: v1
kind: Service
metadata:
  name: wp
spec:
  selector:
    app: wp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
