apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: server-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serverpi
  updatePolicy:
    # updateMode: "Off"
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 10m
      maxAllowed:
        cpu: 1
      controlledResources: ["cpu", "memory"]
